# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: 
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

name: Publish package to the Github
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
      - name: Publish package
        run: mvn clean deploy -Prelease --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}